apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shubhika-rolebinding
  namespace: shubhika-ns
subjects:
 - kind: ServiceAccount
   name: shubhika-sa
   namespace: shubhika-ns
roleRef:
   kind: Role 
   name: shubhika-role
   apiGroup: rbac.authorization.k8s.io
